name: CD github runner

on:
  push:
    branches: 
      - main
      - feature/**
  pull_request:
    branches: 
      - main
      - feature/**

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull paulamariapires/user:latest

      
