name: CD github runner

on:
  push:
    branches: 
      - feature/**

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: pull docker image for docker-compose.yaml
        run: sudo docker pull paulamariapires/new-image:latest