name: CD github runner

on:
  push:
    branches: 
      - feature/**

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull docker image for docker-compose.yaml .
        run: docker pull paulamariapires/user:latest