name: CI

on:
  push:
    branches: 
      - main
      - feature/**
  pull_request:
    branches: 
      - main
      - feature/**

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test with Maven
        run: mvn -B -f user/pom.xml clean verify


  docker_build_and_push:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/user:${{ github.sha }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/user:${{ github.sha }}
